### ISSUE TITLE
[ Week 1 ] 1주차 워크북 미션 

### ISSUE THREAD

**Issue by fsdffds** [DS-UMC-7th/UMC-7th-Blue#1]
### 🛠 Mission

Todo List (HTML, CSS, JS)

### 📝 To-do

- [x]  `제목`, `해야 할 일을 작성할 수 있는 칸`, `해야 할 일/해낸 일을 표시하는 UI`를 만들어 주세요.
- [x]  해야 할 일을 작성할 수 있는 `input 컴포넌트`에 내용을 작성하고, **`ENTER`**를 입력하면 `해야 할 일`에 작성한 할 일이 추가 되도록 해주세요.
- [x]  해야 할 일의 완료를 누르면 해당할 일이 `해낸 일`로 이동하도록 해주세요.
- [x]  해낸 일의 삭제를 누르면 `삭제`되도록 해주세요.

### 🔍 접근 방법

createElement, innerHTML, appendChild, addEventListener등을 이용해 코드를 작성했다.
