### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션2

### ISSUE THREAD

**Issue by fsdffds** [DS-UMC-7th/UMC-7th-Blue#15]
### 🛠 Mission

**미션 2. QueryParameter 활용 검색 기능 구현**

### 📝 To-do

- [x]  `Styled-Components`를 활용해주세요
- [x]  기존에 만들었던, `movie-card 컴포넌트`를 재사용해주세요.

- [x] 영화 제목 검색어를 입력하지 않는 경우 (/search 경로에 처음 온 경우)
- [x] 영화 제목 검색어를 입력한 경우
- [x] 영화 검색어를 입력했으나, 해당 검색어의 영화 데이터가 존재하지 않는 경우.
- [x] 로딩 중인 경우, 아래와 같은 Skeleton UI를 만들어주세요!

### 🔍 접근 방법

6주차 워크북
